version: '3.8'

services:
  app:
    build: .
    ports:
      - "4050:4370"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=gulzodakhan
      - DB_NAME=movies
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gulzodakhan
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
